### ISSUE TITLE
[v2] Localize assets from CDNs

### ISSUE THREAD

**Issue by tabacitu** [DigitallyHappy/assets#2]
This same package could/should also solve the problem of localizing CDN assets.

We could add:
- [x] a config variable, so that the dev can choose his assets to be automatically localized (or not);
- [x] when an item is first loaded, if that asset is from a CDN (we know that because it begins with `http://`, `https://` or `://`), we check if it doesn't also exist on the local file system (`storage/app/public/assets/localized/`); 
    - [x] if it's been localized, we use the local path instead;
    - [ ] if it has NOT been localized, we add that asset to a queue of files to be localized;
- [ ] when running the queue, if the file hasn't been localized in the meantime, each CDN file will be pulled from the CDN and put into `storage/app/public/assets/localized/` so it can be used from there next time;

After that, the docs could also have a section with something like:

```php
// FOR ASSETS FROM CDNs
@asset('https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js')
// will output <link href="{{ asset('https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js')"> the first time
// and it will add 'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js' to a queue of files to be downloaded;
// after that queue has been run (you choose how often), the file has been "localized", which means it's
// also available in your /public/assets/localized/cdn.jsdelivr.net/npm/axios/dist/axios.min.js
// so this package will just load it from there instead, by outputting
// will output <link href="{{ asset('assets/localized/cdn.jsdelivr.net/npm/axios/dist/axios.min.js')">
//
// This has HUUUGE power, because now you can use CDN assets just like they were local. You do NOT have to
// provide them in your public directory, this package will do it for you.
```

**Comment by tabacitu** [comment]
We should _probably_ also provide a way to localize ALL assets. Packages could provide a way to tell `AssetManager` directories where they hold blade files that use assets from CDNs. Then when you run `php artisan assets:localize` it would have a list of directories, go through all the blade files there, parse them to get URLs and localize everything in one command.

**Comment by tabacitu** [comment]
Brain dump with @promatik 

```php

@basset('https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.2.0/tinymce.min.js')

/public/basset/cdnjs.cloudflare.com/ajax/libs/tinymce/6.2.0/tinymce.min.js

---

php artisan basset:install
- add to .gitignore
- add to composer.json

php artisan basset:internalize
```

**Comment by tabacitu** [comment]
Would fix https://github.com/Laravel-Backpack/ideas/issues/116#issuecomment-993374400

**Comment by promatik** [comment]
Can wait to do it 🙌

**Comment by promatik** [comment]
This is fixed by https://github.com/DigitallyHappy/assets/pull/14
