### ISSUE TITLE
[v2] Refactor `AssetManager`

### ISSUE THREAD

**Issue by tabacitu** [DigitallyHappy/assets#3]
I think we can call the class `LoadedAssets`. That way it'd make sense to call:

```php
LoadedAssets::add($asset_path) // instead of markAssetAsLoaded
LoadedAssets::has($asset_path) // instead of isAssetLoaded
LoadedAssets::get() // instead of getLoadedAssets
```

Then again, why not make `LoadedAssets` be an instance of `Collection`? More than that, a Collection of a new `Asset` object:

```
class Asset
{
    public $path;
    public $type; // style or script
    protected $id; // generated by constructor if not given

    public function __construct($path, $id = null) {
        $this->path = $path;
        $this->id = $path;
        // $this->type = 'automatically set depending on extension';
    }

    public function echo()
    {
         // spit it out a <?php ?> script, depending on if it's style or script
     }
}
```

Then we could do:
```php
LoadedAssets::all();
LoadedAssets::where('path', $asset_path);
LoadedAssets::has($asset_path);
LoadedAssets::push($asset_path);
```

The benefit of having an `Asset` object is that we can then add more features to it. For example we could add:
```php
public function isLocal() {}  // whether the path is local, HTTP or HTTPS
public function isExternal() {} // the opposite of the above
public function localize() {} // if the asset is from a CDN, put it on the local filesystem with a conventional public path, so that next time we can get it from there
public function getPath() {} // gets the path to the file... local if the asset is local, URL if the asset is from CDN; if both (the asset is from CDN but has been localized) it'll get the local path
public function addToLocalizingQueue() {} // if the asset is from CDN, this would add the URL to a queue, which once in a while will localize the CDN assets
```

Something like the above. Then we could have a simple `@loadAsset()` blade directive which:
- echoes `<link>` or `<script>` automatically depending on the file extension;
- if the localizing queue has been enabled, when `@loadAsset('https://some/path/to/cdn/file.js')` has been called, it will
    - check if the file exists at the standard localized path (`public/assets/localized/some/path/to/cdn/file.js`)
        - if so, it'll load that local asset;
        - otherwise, it'll load the asset from the CDN;

**Comment by promatik** [comment]
This cases are also covered by bassets 🎉

**Comment by tabacitu** [comment]
Awesome. I'd still keep this open for one more week, until we move everything to `backpack/bassets`. It was about code architecture, and my spidey sense does say that the current code is a bit messy, and we can improve it by creating a `Basset` object, and a `Bassets` collection where we store those objects. But I'm not 100% sure, I'll know more after the code is in a separate repo... we can do a code quality check after we've fixed all bugs.
