### ISSUE TITLE
[v2] Cachebusting string

### ISSUE THREAD

**Issue by tabacitu** [DigitallyHappy/assets#4]
We could add a config option, if the dev would also like us to tag add `?v=8a9hafha9h` to the end of the echoed string, for cachebusting.

**Comment by promatik** [comment]
@tabacitu should we implement this one?

I think it makes some sense ... Developers may set a cachebusting variable for ALL the bassets, should them?

**Comment by tabacitu** [comment]
Totally agree. I've added a corresponding issue in `backpack/bassets`, to do it there. There is never going to be a v2 of `digitallyhappy/assets`, we're just going to recommend everyone use Bassets instead.

So let's move this conversation to https://github.com/Laravel-Backpack/bassets/issues/6
