### ISSUE TITLE
[v1] allow dev to specify extra attributes on the HTML element

### ISSUE THREAD

**Issue by tabacitu** [DigitallyHappy/assets#7]
If loading something from a CDN, the dev might want to pass `integrity` and `crossorigin`. Or hell, maybe even something for lazy-loading. Currently we have no way of doing that. So after #6 I think we should add a second parameter, so that you can do:

```php
@loadOnce('http://domain.com/some.js', [
    'integrity' => 'sha256-0YPKAwZP7Mp3ALMRVB2i8GXeEndvCq3eSl/WsAl1Ryk=',
    'crossorigin' => 'anonymous',
])
```

It's not pretty, but... it should be useful. The implementation isn't difficult at all, it's basically the same thing we do in the [`script` widget in Backpack](https://github.com/Laravel-Backpack/CRUD/blob/4.2/src/resources/views/base/widgets/script.blade.php). And this parameter would be optional, so it'd be a non-breaking change.

Just writing it out so we don't forget about it.

**Comment by promatik** [comment]
We can close this one since bassets allows to set tag attributes 🎉
